import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css"; 
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>News Feed</h1>
        <div className={styles.grid}>
          <Link href="/news">
            <div className={styles.card}>
                <h2>TOP STORIES <span>-&gt;</span></h2>
                <p>Find out all the trending news stories and&nbsp;more!</p>
            </div>
          </Link>
        </div>
      </main>
    </>
  )
}
