import { useState } from "react"; 
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css"; 
import Link from "next/link";

export default function Home() {
  const [query, getQuery] = useState();
  const router = useRouter();
  const handleOnChange = e => getQuery(e.target.value);
  const handleOnSubmit = e => {
    e.preventDefault() 
    router.push(`/news/${query}`)
  } 

  return (
    <div  className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>News Feed</h1> 

        <form onSubmit={handleOnSubmit}>
          <input type="text" onChange={handleOnChange} />
        </form>

        <div className={styles.grid}>
          <Link href="/news">
            <div className={styles.card}>
                <h2>TOP STORIES &rarr;</h2>
                <p>Find out all the trending news stories and&nbsp;more!</p>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <span className={styles.logo}>
          {/* <Image src="/public/vercel.svg" /> */}
        </span>
      </footer>

    </div>
  )
}
