import { useState } from "react"; 
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css"; 
import Link from "next/link";

export default function Home() { 
  const links = [
    {
      title: "Top Stories", 
      desc: "Read articles currently on the homepage of the New York Times", 
      path: "top-stories"
    }, 
    {
      title: "Popular", 
      desc: "Read the most popular articles on the New York Times", 
      path: "popular"
    }
  ];

  const [query, getQuery] = useState();
  const router = useRouter();
  const handleOnChange = e => getQuery(e.target.value);
  const handleOnSubmit = e => {
    e.preventDefault() 
    router.push(`/search/${query}`)
  } 

  return (
    <div  className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>News Feed</h1> 

        <form onSubmit={handleOnSubmit}>
          <input type="text" onChange={handleOnChange} />
        </form>

        <div className={styles.grid}> 
          {links.map(link => {
            return (
              <Link key={link.path} href={`news/${link.path}`}>
                <span className={styles.card}>
                  <h2>{link.title} &rarr;</h2>
                  <p>{link.desc}</p>
                </span>
              </Link>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <span className={styles.logo}>
          {/* <Image src="/public/vercel.svg" /> */}
        </span>
      </footer>
    </div>
  )
}
