import Head from "next/head";
import Layout from "../../components/Layout";
import List from "../../components/List";
import { results as apiResults } from "../api/index"; 
import Link from "next/link";

export default function Posts(props) {
    return (
        <Layout>
            <Head>
                <title>{props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <List {...props} />
        </Layout>
    );
}

const API_KEY = process.env.API_KEY; 

export async function getStaticPaths() {
    const data = await apiResults(`https://api.nytimes.com/svc/news/v3/content/section-list.json?api-key=${API_KEY}`);

    const paths = data.results ? data.results.map((result) => ({
        params: { section: result.section }
    })) : [];

    return {
        paths,
        fallback: false, 
    };
}

export async function getStaticProps({ params }) {
    const data = await apiResults(`https://api.nytimes.com/svc/news/v3/content/nyt/${params.section}.json?api-key=${API_KEY}`);

    return {
        props: {
            results: data || [], 
            title:  "Section: " + params.section,
        }
    }
}