import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <p>Welcome to my eLearning Platform</p>
        </div>

        <div className={styles.grid}>
          <Link href="/learn/next" className={styles.card}>
            <h2>Learn NextJS <span>-&gt;</span></h2>
            <p>Find in-depth information about Next.js features and&nbsp;API.</p>
          </Link>

          <Link href="/learn/react" className={styles.card}>
            <div>
              <h2>Learn React<span>-&gt;</span></h2>
              <p>Learn about React.js in an interactive course with&nbsp;quizzes!</p>
            </div>
          </Link>

          <Link href="/learn/vue" className={styles.card}>
            <div>
              <h2>Learn Vue<span>-&gt;</span></h2>
              <p>Learn about Vue.js in an interactive course with&nbsp;quizzes!</p>
            </div>
          </Link>

          <Link href="/learn/angular" className={styles.card}>
            <div>
              <h2>Learn Angular<span>-&gt;</span></h2>
              <p>Learn about Angular.js in an interactive course with&nbsp;quizzes!</p>
            </div>
          </Link>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy <span>-&gt;</span></h2>
            <p>Instantly deploy your Next.js site to a shareable URL with&nbsp;Vercel.</p>
          </a>
        </div>
      </main>
    </>
  );
};
